### ISSUE TITLE
MKS PWC V3.0

### ISSUE THREAD

**Issue by artem9** [makerbase-mks/MKS-Power-Control#1]
Hello! On your sales page I see information about new version 3.0. Could you add information about updates?
Also I have question about firmware settings. I have printer based on MKS Robin Nano V1.2 board with installed Marlin (2.0.X) firmware. Current instruction includes settings for Original MSK firmware. Could you provide settings for Marlin firmware?

**Comment by makerbase-mks** [comment]
Hi! I has upload information about MKS PWC V3.0. I will perfect tutorial about how to use it.
