### ISSUE TITLE
Printer doesn't boot when inserted fans into 12/24V connectors

### ISSUE THREAD

**Issue by artem9** [makerbase-mks/MKS-Power-Control#2]
Today I installed the MKS PWC module into my 3D printer - TwoTrees Sapphire Pro. It has a mainboard MKS Robin Nano V1.2. I also made a fork from your "MKS Marlin 2.0 Firmware" repo, this is a configuration that I compiled and installed - https://github.com/artem9/Mks-Robin-Nano-Marlin2.0-Firmware/tree/sapphire-pro. Printer with this configuration can turn on/off (works as usual), but when I try to connect fans to the motherboard - it doesn't turn on anymore. 
This is the final build result - https://photos.app.goo.gl/SfETfBV3voTCGtVj6

**Comment by makerbase-mks** [comment]
I think, you need to press and hold the switch for a while, wait for the motherboard to boot, everything will be normal

**Comment by mks-viva** [comment]
Is this problem solved?

**Comment by mks-viva** [comment]
I will close this question temporarily.
