### ISSUE TITLE
what does the MKS PWC 3.0 do in case of Power loss?

### ISSUE THREAD

**Issue by nictronik99** [makerbase-mks/MKS-Power-Control#3]
What is the PWC capable of doing in the event of a power loss? Is it able to save the position if I enable Power loss recovery in Marlin that does not save the position on the SD layer by layer?

**Comment by nictronik99** [comment]
Can anyone answer? The question is quite simple! @makerbase-mks

**Comment by makerbase-mks** [comment]
Hi! MKS PWC does not affect the power loss function.

**Comment by nictronik99** [comment]
But can't I use the pwc module with the ups module?

**Comment by makerbase-mks** [comment]
Because MKS PWC and MKS UPS has detect function, for example, if AC power loss when printing, MKS PWC PW_DET has signal, AC power off and then MKS UPS detect AC power loss, Z axis move...

**Comment by mks-viva** [comment]
@nictronik99 Is this problem solved?

**Comment by nictronik99** [comment]
> @nictronik99 Is this problem solved?

Yes, thanks
